# Generated by Django 5.0.1 on 2024-04-10 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
                ('date_time', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='images/')),
                ('product_description', models.TextField()),
            ],
        ),
    ]
